version: '3.8'

services:
  # CONTENEDOR 1: La Base de Datos (PostgreSQL)
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: monterosa_db
      POSTGRES_USER: monterosa_user
      POSTGRES_PASSWORD: superpassword123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # CONTENEDOR 2: Tu Código (Django + Gunicorn)
  web:
    build: .
    restart: always
    # 1. Empaqueta el diseño, 2. Crea las tablas en Postgres, 3. Enciende Gunicorn
    command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn backend_central.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - USA_DOCKER=True
      - POSTGRES_DB=monterosa_db
      - POSTGRES_USER=monterosa_user
      - POSTGRES_PASSWORD=superpassword123
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

  # CONTENEDOR 3: El Servidor Web (Nginx)
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web

# Declaramos los volúmenes físicos persistentes
volumes:
  postgres_data:
  static_volume:
  media_volume: